### ISSUE TITLE
Unable to Compile After Successful CMake Configuration

### ISSUE THREAD

**Issue by duzhenpeng** [edisonlee0212/EvoEngine#50]
I am reaching out regarding an issue I encountered while attempting to build the project. While I was able to successfully configure the project using CMake, I encountered errors during the compilation process, regardless of whether I used Ninja or Visual Studio 17 2022.

<img width="499" alt="3f1dd0e58d5c35a38dff71eb399ec2f" src="https://github.com/user-attachments/assets/e90fa2ec-af10-45e4-8c1d-54edd73fb2db">

<img width="841" alt="5b82098d8b7768d4ea072df332b59cd" src="https://github.com/user-attachments/assets/36062678-774f-40b2-a635-b494f6b6598a">

_**cmake -G "Visual Studio 17 2022" -A Win32 ..**_
<img width="531" alt="095926d718c6cacd1c9335364a9b85b" src="https://github.com/user-attachments/assets/69a7c392-e977-4010-846c-365ed3928465">

**Comment by edisonlee0212** [comment]
You need to change the configuration to x64-Debug or x64-Release. We do not support 32bit compilation.

**Comment by duzhenpeng** [comment]
We have successfully compiled the project for the x64 architecture. However, upon attempting to execute demo.exe, it fails to run as expected. Here are a few key observations:
<img width="807" alt="290e50e6d1c2bc4136b6f6dec9442ad" src="https://github.com/user-attachments/assets/44bf68ee-d06b-4057-9884-9c090c392889">
<img width="670" alt="6e4fd908fd4cbc33c5ac1e7d96c746f" src="https://github.com/user-attachments/assets/ca00a150-e56e-4634-9d93-49dd516787d6">

**Comment by edisonlee0212** [comment]
The "ALL_BUILD" is a building target including building all libraries and executables defined by SDK. Itself is not executable. Looks like you successfully built all targets. 
To run any of the executables, select one of them from "Executables" (E.g. DemoApp, DigitalAgricultureApp, EcoSysLabApp, etc.) from VS Solution Explorer as Startup Project (Right click on the project ->Set as Startup Project) and you will be able to run it.
Different executables are implemented for my different research projects. DemoApp contains the classic Sponza scene for demonstrating rendering capabilities.

![image](https://github.com/user-attachments/assets/e1e46d02-1484-43dd-910d-5a31badea5e4)

**Comment by duzhenpeng** [comment]
I am currently able to successfully run DemoApp, but I am encountering errors when trying to run other demos, such as TreedatageneratorApp. 
![evoengine](https://github.com/user-attachments/assets/a008bb0c-4ad3-42e7-9778-3c0b9a75ac6d)

![QQ截图20241201185558](https://github.com/user-attachments/assets/fe6a6f20-3915-459e-8596-d980f3a2af96)

**Comment by edisonlee0212** [comment]
This is for one of our current on-going research projects. I'm sorry but I can't provide any help for this. If you are able to run DemoApp.exe this means you have successfully compiled and run the framework. I'm closing this ticket because of this.
